### ISSUE TITLE
With a fresh install i go an ERROR: audio conversion failed

### ISSUE THREAD

**Issue by yodatak** [flathub/com.github.JannikHv.Gydl#6]
With the flathub install i use this link and click on dowload https://youtu.be/1vrEljMfXYo
Then it failed : 
I got this in the console : 
[youtube] 1vrEljMfXYo: Downloading webpage
[youtube] 1vrEljMfXYo: Downloading video info webpage
[youtube] 1vrEljMfXYo: Extracting video information
[download] Destination: /home/yodatak/Tlchargements/John_Denver_-_Take_Me_Home_Country_Roads_Audio.webm
[download] 100% of 3.14MiB in 00:00
[ffmpeg] Destination: /home/yodatak/Tlchargements/John_Denver_-_Take_Me_Home_Country_Roads_Audio.mp3
ERROR: audio conversion failed: file:/home/yodatak/Tlchargements/John_Denver_-_Take_Me_Home_Country_Roads_Audio.mp3: Invalid argument

Maybe its because of the locale ? In on a french system and it don't show Téléchargements but Tlchargements

**Comment by nedrichards** [comment]
This is fixed by https://github.com/flathub/com.github.JannikHv.Gydl/commit/7ff59619213c1c9ce59921bbea2ea762b8fa1dc6
